source "https://rubygems.org"

if ENV["RELAY_UI_PATH"]
  gem "relay_ui", path: ENV["RELAY_UI_PATH"]
else
  gem "relay_ui"
end

gem "rails", "~> 8.0.1"
gem "propshaft"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"
gem "jsbundling-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "phlex-rails"
gem "tailwindcss-ruby"
gem "tailwindcss-rails"
gem "tabler_icons_ruby"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :development do
  gem "web-console"
  gem "guard"
  gem "guard-livereload"
end
