name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint_gem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run linter
        run: bundle exec rubocop -f github
  lint_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: docs
      - name: Bundle install
        run: bundle install
        working-directory: ./docs
        env:
          RELAY_UI_PATH: 
      - name: Run linter
        run: bundle exec rubocop -f github
        working-directory: docs